theme: jekyll-theme-modernist
title: Welcome to Jellwood's Blog!
description: Stay up to date on Code and Ethics!

Hello! My name is Jonathan Ellwood and I am a computer science
student at College of Charleston. I am in my last year and I intend to go into
Software Engineering post-graduation. In my free time, I like to play video games,
although this summer I also spent a berth of time reading academic papers and it is
a very delightful passtime of mine!